{% set name = "apache-airflow-providers-alibaba" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_alibaba-{{ version }}.tar.gz
  sha256: 59fe7f0d3378dd3d16896b3724e50a53b0c2c41cc4caa4ec340ab7496a9317a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.11.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - oss2 >=2.14.0
    - alibabacloud-adb20211201 >=1.0.0
    - alibabacloud-tea-openapi >=0.3.7

test:
  imports:
    - airflow.providers.alibaba
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-alibaba for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/alibaba/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
