{% set name = "apache-airflow-providers-alibaba" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_alibaba-{{ version }}.tar.gz
  sha256: 50201e9af9ecea3b0ae3d9ce72df7a5e549b924b0ea8c58c859bfdf5d0f0d0b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - alibabacloud-adb20211201 >=1.0.0
    - alibabacloud-tea-openapi >=0.3.7
    - apache-airflow >=2.9.0
    - oss2 >=2.14.0

test:
  imports:
    - airflow.providers.alibaba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-alibaba for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/alibaba/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
