{% set name = "apache-airflow-providers-alibaba" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-alibaba-{{ version }}.tar.gz
  sha256: c78e7270988f068103559aa2d3ca8a78a4c5edbb9856cb5a7ebc2bcd6afb3342

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - alibabacloud-adb20211201 >=1.0.0
    - alibabacloud-tea-openapi >=0.3.7
    - apache-airflow >=2.4.0
    - oss2 >=2.14.0

test:
  imports:
    - airflow.providers.alibaba
    - airflow.providers.alibaba.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-alibaba package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
