{% set name = "apache-airflow-providers-alibaba" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_alibaba-{{ version }}.tar.gz
  sha256: 546f9f269e27be9b61d51ff04e06cd7aff40c946b419f25aa249d2b1151759b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - alibabacloud-adb20211201 >=1.0.0
    - alibabacloud-tea-openapi >=0.3.7
    - apache-airflow >=2.7.0
    - oss2 >=2.14.0

test:
  imports:
    - airflow.providers.alibaba
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-alibaba for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/alibaba/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
