context:
  name: apache-airflow-providers-alibaba
  version: 3.3.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_alibaba-${{ version }}.tar.gz
  sha256: 0d4c5613e3e28cd803ec4dc388e3f2b83df58b3ff2ae994247850a3b1237c22c

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - oss2 >=2.14.0
    - pyodps >=0.12.2.2
    - alibabacloud_adb20211201 >=1.0.0
    - alibabacloud_tea_openapi >=0.3.7
tests:
  - python:
      imports:
        - airflow.providers.alibaba
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-alibaba for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-alibaba/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
